[package]
name = "deploy"
version = "0.1.0"
authors = ["kkua"]
edition = "2018"

[dependencies]
pbr = "1"
libssh2-sys = "=0.2.11"
ssh2 = "0.3.3"
md5 = "0.6"
toml = "0.5.3"
serde = "1.0"
serde_derive = "1.0"